### ISSUE TITLE
Great package, but..

### ISSUE THREAD

**Issue by simplenotezy** [karlito40/fix-irregular-whitespace#2]
It needs to be able to do it automagically on save before it would save me any real time

**Comment by karlito40** [comment]
Oh god sorry. I didn't know someone open an issue on my project. I miss the notification somehow.

I agree with you on this one. I think i've tried to do that and fallback to the save solution. I don't remember the reason though. My guess is that i have not found the correct api to do that.

I've moved on some other project for now as this one serves my need. I don't encounter any weird irregular whitespace  anymore since i'm using it.

Feel free to send a PR if you know how to pull it off. Or if you can point me to the vscode API that will allow us to do that, i'll may considerate and investigate it

**Comment by simplenotezy** [comment]
Ah no worries @karlito40 thanks for provding the package to the community anyhow - great job! 😊

**Comment by MohamedLamineAllal** [comment]
This issue should be closed ! No!

**Comment by karlito40** [comment]
I think that this issue should stay open in case someone want to do it. It will be a great feature to have.
